"use client";

import { useActionState } from "react";
import { updateProfileAction } from "@/app/(dashboard)/settings/actions";

export function SettingsForm({ displayName, email }: { displayName: string; email: string }) {
  const [state, action, pending] = useActionState(updateProfileAction, { success: false, error: null });
  const input = "mt-2 w-full border-2 border-black bg-white px-4 py-4 font-body outline-none focus:border-brand focus:shadow-hard-primary disabled:bg-surface-high disabled:text-on-surface-variant";
  return <form action={action} className="border-2 border-black bg-white p-6 shadow-hard md:p-8"><div className="mb-7 flex items-center gap-4 border-b-2 border-black pb-5"><div className="flex h-12 w-12 items-center justify-center border-2 border-black bg-brand-fixed"><span className="material-symbols-outlined text-brand">person</span></div><div><h2 className="font-headline text-xl font-bold uppercase">Personal information</h2><p className="text-sm text-on-surface-variant">How your name appears across the dashboard.</p></div></div><div className="grid gap-6 md:grid-cols-2"><label className="font-headline text-xs font-bold uppercase tracking-wider">Display name<input name="display_name" required minLength={2} maxLength={60} defaultValue={displayName} autoComplete="name" className={input} /></label><label className="font-headline text-xs font-bold uppercase tracking-wider">Email address<input type="email" value={email} disabled className={input} /><span className="mt-2 block font-body text-[11px] font-medium normal-case tracking-normal text-on-surface-variant">Email changes are currently managed through account support.</span></label></div>{state.error && <p role="alert" className="mt-5 border-2 border-danger bg-red-50 p-3 text-sm font-medium text-danger">{state.error}</p>}{state.success && <p role="status" className="mt-5 border-2 border-black bg-[#c8f4d4] p-3 text-sm font-bold">Profile updated successfully.</p>}<button type="submit" disabled={pending} className="mt-7 inline-flex items-center gap-2 border-2 border-black bg-black px-6 py-4 font-headline text-sm font-bold uppercase text-white shadow-hard-sm transition-all hover:bg-brand active:translate-x-0.5 active:translate-y-0.5 active:shadow-none disabled:opacity-60"><span className="material-symbols-outlined">save</span>{pending ? "Saving…" : "Save changes"}</button></form>;
}
