import { FeedbackActions } from "@/components/admin/feedback-actions";
import { createClient } from "@/lib/supabase/server";

export default async function AdminFeedbackPage() {
  const supabase = await createClient();
  const { data: feedback, error } = await supabase.from("feedback_submissions").select("*").order("created_at", { ascending: false });
  if (error) throw new Error(error.message);
  const items = feedback ?? []; const fresh = items.filter((item) => item.status === "new").length; const resolved = items.filter((item) => item.status === "resolved").length;
  return <div className="space-y-7 p-4 md:p-6 lg:p-8"><div><p className="font-headline text-xs font-bold uppercase tracking-[0.2em] text-brand">Student voice</p><h1 className="mt-2 font-headline text-3xl font-bold uppercase md:text-4xl">Feedback inbox</h1><p className="mt-2 text-on-surface-variant">Review suggestions and close the loop on student concerns.</p></div><div className="grid gap-4 sm:grid-cols-3"><Stat label="All messages" value={items.length} icon="forum" /><Stat label="New" value={fresh} icon="mark_email_unread" /><Stat label="Resolved" value={resolved} icon="task_alt" /></div>{items.length ? <div className="space-y-4">{items.map((item) => <article key={item.id} className={`border-2 border-black bg-white p-5 shadow-hard-sm md:p-6 ${item.status === "new" ? "border-l-[8px] border-l-brand" : ""}`}><div className="flex flex-col justify-between gap-4 md:flex-row md:items-start"><div className="min-w-0"><div className="flex flex-wrap items-center gap-3"><h2 className="font-headline text-lg font-bold">{item.name}</h2><span className={`border-2 border-black px-2 py-1 text-[10px] font-bold uppercase ${item.status === "new" ? "bg-brand-fixed" : item.status === "resolved" ? "bg-[#c8f4d4]" : "bg-[#ffe8a3]"}`}>{item.status}</span></div><a href={`mailto:${item.email}`} className="mt-1 block text-sm font-medium text-brand hover:underline">{item.email}</a><p className="mt-4 max-w-4xl whitespace-pre-wrap text-base leading-relaxed text-on-surface-variant">{item.message}</p><p className="mt-4 text-xs font-bold uppercase text-outline">Received {new Intl.DateTimeFormat("en-PK", { dateStyle: "medium", timeStyle: "short" }).format(new Date(item.created_at))}</p></div><FeedbackActions id={item.id} status={item.status} /></div></article>)}</div> : <div className="border-2 border-black bg-white px-6 py-16 text-center shadow-hard"><span className="material-symbols-outlined text-6xl text-brand">inbox</span><h2 className="mt-4 font-headline text-2xl font-bold uppercase">Inbox is clear</h2><p className="mt-2 text-on-surface-variant">New landing-page feedback will appear here.</p></div>}</div>;
}

function Stat({ label, value, icon }: { label: string; value: number; icon: string }) { return <div className="flex items-center justify-between border-2 border-black bg-white p-5 shadow-hard-sm"><div><p className="font-headline text-3xl font-bold">{value}</p><p className="text-xs font-bold uppercase text-on-surface-variant">{label}</p></div><span className="material-symbols-outlined text-4xl text-brand">{icon}</span></div>; }
