#!/usr/bin/env python3
"""Generate the repeatable ECAT catalog/question migration from mcqs/ecat_mcqs.csv."""

import csv
import json
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CSV_PATH = ROOT / "mcqs" / "ecat_mcqs.csv"
OUTPUT_PATH = ROOT / "supabase" / "migrations" / "20260905120000_add_ecat_test.sql"

EXPECTED_SUBJECT_COUNTS = {
    "english": 210,
    "mathematics": 450,
    "physics": 495,
    "chemistry": 345,
}
VALID_DIFFICULTIES = {"easy", "medium", "hard"}
VALID_CORRECT_OPTIONS = {"a", "b", "c", "d", "e"}


def clean(value: str | None) -> str:
    return (value or "").strip()


def load_and_validate() -> list[dict[str, object]]:
    with CSV_PATH.open(newline="", encoding="utf-8-sig") as source:
        source_rows = list(csv.DictReader(source))

    if len(source_rows) != sum(EXPECTED_SUBJECT_COUNTS.values()):
        raise ValueError(f"Expected 1500 rows, found {len(source_rows)}")

    ids: set[str] = set()
    counts: Counter[str] = Counter()
    rows: list[dict[str, object]] = []

    for line_number, source_row in enumerate(source_rows, start=2):
        external_id = clean(source_row.get("external_id"))
        subject_slug = clean(source_row.get("subject_slug")).lower()
        correct_option = clean(source_row.get("correct_option")).lower()
        difficulty = clean(source_row.get("difficulty")).lower()
        options = {
            label: clean(source_row.get(f"option_{label}"))
            for label in ("a", "b", "c", "d", "e")
        }

        required = {
            "external_id": external_id,
            "subject": clean(source_row.get("subject")),
            "subject_slug": subject_slug,
            "chapter_slug": clean(source_row.get("chapter_slug")),
            "chapter_title": clean(source_row.get("chapter_title")),
            "statement": clean(source_row.get("statement")),
        }
        missing = [name for name, value in required.items() if not value]
        if missing:
            raise ValueError(f"Line {line_number}: missing {', '.join(missing)}")
        if external_id in ids:
            raise ValueError(f"Line {line_number}: duplicate external_id {external_id}")
        if subject_slug not in EXPECTED_SUBJECT_COUNTS:
            raise ValueError(f"Line {line_number}: unexpected subject {subject_slug}")
        if difficulty not in VALID_DIFFICULTIES:
            raise ValueError(f"Line {line_number}: invalid difficulty {difficulty}")
        if correct_option not in VALID_CORRECT_OPTIONS or not options[correct_option]:
            raise ValueError(f"Line {line_number}: invalid or empty correct option")
        if sum(bool(value) for value in options.values()) < 3:
            raise ValueError(f"Line {line_number}: fewer than three answer options")

        ids.add(external_id)
        counts[subject_slug] += 1
        rows.append(
            {
                **required,
                "chapter_num": int(clean(source_row.get("chapter_num")) or 0),
                "node_kind": clean(source_row.get("node_kind")) or "topic",
                "option_a": options["a"] or None,
                "option_b": options["b"] or None,
                "option_c": options["c"] or None,
                "option_d": options["d"] or None,
                "option_e": options["e"] or None,
                "correct_option": correct_option,
                "explanation": clean(source_row.get("explanation")) or None,
                "difficulty": difficulty,
                "source": clean(source_row.get("source")) or "ecat-question-bank",
            }
        )

    if dict(counts) != EXPECTED_SUBJECT_COUNTS:
        raise ValueError(f"Unexpected per-subject counts: {dict(counts)}")
    return rows


def build_sql(rows: list[dict[str, object]]) -> str:
    payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    if "$ecat_questions$" in payload:
        raise ValueError("Migration delimiter occurs in CSV data")

    return f"""-- Generated by scripts/generate_ecat_migration.py from mcqs/ecat_mcqs.csv.
-- Adds ECAT as a data-driven test and imports its verified 1,500-question bank.
begin;

alter table mock_test_blueprints
  add column if not exists marks_per_correct numeric(8,2) not null default 1,
  add column if not exists marks_per_incorrect numeric(8,2) not null default 0,
  add column if not exists marks_per_unanswered numeric(8,2) not null default 0;

insert into entry_tests (
  external_id, slug, name, description, source, is_active, display_order
)
values (
  'ecat-engineering',
  'ecat',
  'ECAT Engineering',
  'Engineering admission test preparation with Mathematics, Physics, Chemistry, and English.',
  'ECAT verified question bank',
  true,
  30
)
on conflict (external_id) do update set
  slug = excluded.slug,
  name = excluded.name,
  description = excluded.description,
  source = excluded.source,
  is_active = excluded.is_active,
  display_order = excluded.display_order;

insert into subjects (external_id, slug, name)
values
  ('english', 'english', 'English'),
  ('mathematics', 'mathematics', 'Mathematics'),
  ('physics', 'physics', 'Physics'),
  ('chemistry', 'chemistry', 'Chemistry')
on conflict (external_id) do update set name = excluded.name;

insert into test_subjects (
  entry_test_id, subject_id, nature_of_questions, difficulty_profile,
  display_order, is_active, deleted_at
)
select et.id, s.id, v.nature, v.profile, v.ord, true, null
from entry_tests et
cross join (values
  ('english', 'Vocabulary, tenses, articles, and sentence structure', '{{"easy":6,"medium":4,"hard":0}}'::jsonb, 0),
  ('mathematics', 'Intermediate-level engineering mathematics and problem solving', '{{"easy":10,"medium":20,"hard":0}}'::jsonb, 1),
  ('physics', 'Conceptual and numerical engineering physics', '{{"easy":12,"medium":13,"hard":5}}'::jsonb, 2),
  ('chemistry', 'Physical, inorganic, and organic chemistry', '{{"easy":8,"medium":17,"hard":5}}'::jsonb, 3)
) as v(subject_slug, nature, profile, ord)
join subjects s on s.slug = v.subject_slug
where et.slug = 'ecat'
on conflict (entry_test_id, subject_id) do update set
  nature_of_questions = excluded.nature_of_questions,
  difficulty_profile = excluded.difficulty_profile,
  display_order = excluded.display_order,
  is_active = true,
  deleted_at = null;

create temporary table ecat_import_stage on commit drop as
select *
from jsonb_to_recordset($ecat_questions${payload}$ecat_questions$::jsonb) as row_data(
  external_id text,
  subject text,
  subject_slug text,
  chapter_num integer,
  chapter_slug text,
  chapter_title text,
  node_kind text,
  statement text,
  option_a text,
  option_b text,
  option_c text,
  option_d text,
  option_e text,
  correct_option text,
  explanation text,
  difficulty text,
  source text
);

insert into topics (
  external_id, subject_id, kind, title, slug, display_order, deleted_at
)
select distinct on (stage.subject_slug, stage.chapter_slug)
  'ecat-' || stage.subject_slug || '-' || stage.chapter_slug,
  subject.id,
  stage.node_kind::topic_kind,
  stage.chapter_title,
  stage.chapter_slug,
  stage.chapter_num,
  null
from ecat_import_stage stage
join subjects subject on subject.slug = stage.subject_slug
order by stage.subject_slug, stage.chapter_slug, stage.chapter_num
on conflict (external_id) do update set
  subject_id = excluded.subject_id,
  kind = excluded.kind,
  title = excluded.title,
  slug = excluded.slug,
  display_order = excluded.display_order,
  deleted_at = null;

insert into questions (
  external_id, subject_id, topic_id, difficulty, statement,
  explanation, source, moderation_status, review_note, deleted_at
)
select
  stage.external_id,
  subject.id,
  topic.id,
  stage.difficulty::difficulty,
  stage.statement,
  stage.explanation,
  stage.source,
  'approved'::moderation_status,
  null,
  null
from ecat_import_stage stage
join subjects subject on subject.slug = stage.subject_slug
join topics topic
  on topic.external_id = 'ecat-' || stage.subject_slug || '-' || stage.chapter_slug
on conflict (external_id) do update set
  subject_id = excluded.subject_id,
  topic_id = excluded.topic_id,
  difficulty = excluded.difficulty,
  statement = excluded.statement,
  explanation = excluded.explanation,
  source = excluded.source,
  moderation_status = excluded.moderation_status,
  review_note = null,
  deleted_at = null;

-- Reset imported answer flags first so corrected source answers remain re-importable.
update question_options option_row
set is_correct = false
from questions question
join ecat_import_stage stage on stage.external_id = question.external_id
where option_row.question_id = question.id;

insert into question_options (
  question_id, option_label, content, is_correct, display_order
)
select
  question.id,
  option_data.label,
  option_data.content,
  option_data.label = stage.correct_option,
  option_data.ord
from ecat_import_stage stage
join questions question on question.external_id = stage.external_id
cross join lateral (values
  ('a', stage.option_a, 0),
  ('b', stage.option_b, 1),
  ('c', stage.option_c, 2),
  ('d', stage.option_d, 3),
  ('e', stage.option_e, 4)
) as option_data(label, content, ord)
where nullif(btrim(option_data.content), '') is not null
on conflict (question_id, option_label) do update set
  content = excluded.content,
  is_correct = excluded.is_correct,
  display_order = excluded.display_order;

insert into question_tests (
  question_id, entry_test_id, usage_type, difficulty
)
select
  question.id,
  entry_test.id,
  'practice'::question_usage,
  stage.difficulty::difficulty
from ecat_import_stage stage
join questions question on question.external_id = stage.external_id
cross join entry_tests entry_test
where entry_test.slug = 'ecat'
on conflict (question_id, entry_test_id) do update set
  usage_type = excluded.usage_type,
  difficulty = excluded.difficulty;

insert into mock_test_blueprints (
  external_id, entry_test_id, name, description, duration_seconds,
  total_questions, marks_per_correct, marks_per_incorrect,
  marks_per_unanswered, is_active, display_order
)
select
  'ecat-engineering-full-mock',
  entry_test.id,
  'ECAT Engineering Full Mock',
  'A strict 100-minute simulation with English (10), Mathematics (30), Physics (30), and Chemistry (30). Each correct answer awards 4 marks; there is no negative marking.',
  6000,
  100,
  4,
  0,
  0,
  true,
  0
from entry_tests entry_test
where entry_test.slug = 'ecat'
on conflict (external_id) do update set
  entry_test_id = excluded.entry_test_id,
  name = excluded.name,
  description = excluded.description,
  duration_seconds = excluded.duration_seconds,
  total_questions = excluded.total_questions,
  marks_per_correct = excluded.marks_per_correct,
  marks_per_incorrect = excluded.marks_per_incorrect,
  marks_per_unanswered = excluded.marks_per_unanswered,
  is_active = excluded.is_active,
  display_order = excluded.display_order;

insert into mock_blueprint_slots (
  blueprint_id, test_subject_id, question_count, past_paper_min,
  practice_max, difficulty_mix, display_order
)
select
  blueprint.id,
  test_subject.id,
  slot.question_count,
  0,
  slot.question_count,
  slot.mix,
  slot.ord
from mock_test_blueprints blueprint
cross join (values
  ('english', 10, '{{"easy":6,"medium":4,"hard":0}}'::jsonb, 0),
  ('mathematics', 30, '{{"easy":10,"medium":20,"hard":0}}'::jsonb, 1),
  ('physics', 30, '{{"easy":12,"medium":13,"hard":5}}'::jsonb, 2),
  ('chemistry', 30, '{{"easy":8,"medium":17,"hard":5}}'::jsonb, 3)
) as slot(subject_slug, question_count, mix, ord)
join entry_tests entry_test on entry_test.slug = 'ecat'
join subjects subject on subject.slug = slot.subject_slug
join test_subjects test_subject
  on test_subject.entry_test_id = entry_test.id
 and test_subject.subject_id = subject.id
where blueprint.external_id = 'ecat-engineering-full-mock'
on conflict (blueprint_id, test_subject_id) do update set
  question_count = excluded.question_count,
  past_paper_min = excluded.past_paper_min,
  practice_max = excluded.practice_max,
  difficulty_mix = excluded.difficulty_mix,
  display_order = excluded.display_order;

do $$
declare
  imported_count integer;
  invalid_option_count integer;
  invalid_answer_count integer;
  slot_total integer;
begin
  select count(*) into imported_count
  from question_tests link
  join entry_tests test on test.id = link.entry_test_id
  join questions question on question.id = link.question_id
  where test.slug = 'ecat' and question.external_id like 'ecat-%';

  select count(*) into invalid_option_count
  from (
    select question.id
    from ecat_import_stage stage
    join questions question on question.external_id = stage.external_id
    join question_options option_row on option_row.question_id = question.id
    group by question.id
    having count(*) not between 3 and 5
  ) invalid;

  select count(*) into invalid_answer_count
  from (
    select question.id
    from ecat_import_stage stage
    join questions question on question.external_id = stage.external_id
    join question_options option_row on option_row.question_id = question.id
    group by question.id
    having count(*) filter (where option_row.is_correct) <> 1
  ) invalid;

  select coalesce(sum(slot.question_count), 0) into slot_total
  from mock_blueprint_slots slot
  join mock_test_blueprints blueprint on blueprint.id = slot.blueprint_id
  where blueprint.external_id = 'ecat-engineering-full-mock';

  if imported_count <> 1500 then
    raise exception 'ECAT import expected 1500 linked questions, found %', imported_count;
  end if;
  if invalid_option_count <> 0 or invalid_answer_count <> 0 then
    raise exception 'ECAT validation failed: % invalid option counts, % invalid answer keys',
      invalid_option_count, invalid_answer_count;
  end if;
  if slot_total <> 100 then
    raise exception 'ECAT blueprint expected 100 questions, found %', slot_total;
  end if;
end $$;

commit;
"""


def main() -> None:
    rows = load_and_validate()
    OUTPUT_PATH.write_text(build_sql(rows), encoding="utf-8")
    print(f"Generated {OUTPUT_PATH.relative_to(ROOT)} with {len(rows)} questions")


if __name__ == "__main__":
    main()
