#!/usr/bin/env python3
"""Generate the repeatable FAST-NUCES import migration from its CSV question bank."""

import argparse
import csv
import json
import re
from collections import Counter
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CSV = Path.home() / "Downloads" / "fast_nuces_1000_mcqs.csv"
OUTPUT_PATH = ROOT / "supabase" / "migrations" / "20260907180000_add_fast_nuces_test.sql"

EXPECTED_SUBJECT_COUNTS = {
    "advanced-mathematics": 417,
    "basic-mathematics": 167,
    "english": 249,
    "iq-analytical-reasoning": 167,
}
EXPECTED_USAGE_COUNTS = {"past_paper": 394, "practice": 606}
VALID_DIFFICULTIES = {"easy", "medium", "hard"}
VALID_ANSWERS = {"a", "b", "c", "d"}


def clean(value: str | None) -> str:
    return (value or "").strip()


def load_rows(csv_path: Path) -> list[dict[str, object]]:
    with csv_path.open(newline="", encoding="utf-8-sig") as source:
        source_rows = list(csv.DictReader(source))

    if len(source_rows) != 1000:
        raise ValueError(f"Expected 1000 rows, found {len(source_rows)}")

    ids: set[str] = set()
    subject_counts: Counter[str] = Counter()
    usage_counts: Counter[str] = Counter()
    rows: list[dict[str, object]] = []

    for line_number, source_row in enumerate(source_rows, start=2):
        external_id = clean(source_row.get("external_id"))
        subject = clean(source_row.get("subject"))
        subject_slug = clean(source_row.get("subject_slug")).lower()
        chapter_slug = clean(source_row.get("chapter_slug")).lower()
        chapter_title = clean(source_row.get("chapter_title"))
        statement = re.sub(
            r"^Form item\s+\d+:\s*",
            "",
            clean(source_row.get("statement")),
            flags=re.IGNORECASE,
        )
        difficulty = clean(source_row.get("difficulty")).lower()
        correct_option = clean(source_row.get("correct_option")).lower()
        source_label = clean(source_row.get("source")).lower()
        usage_type = "past_paper" if source_label == "past-paper-style" else "practice"
        options = {
            label: clean(source_row.get(f"option_{label}"))
            for label in ("a", "b", "c", "d")
        }

        required = {
            "external_id": external_id,
            "subject": subject,
            "subject_slug": subject_slug,
            "chapter_slug": chapter_slug,
            "chapter_title": chapter_title,
            "statement": statement,
        }
        missing = [key for key, value in required.items() if not value]
        if missing:
            raise ValueError(f"Line {line_number}: missing {', '.join(missing)}")
        if external_id in ids:
            raise ValueError(f"Line {line_number}: duplicate external_id {external_id}")
        if subject_slug not in EXPECTED_SUBJECT_COUNTS:
            raise ValueError(f"Line {line_number}: unexpected subject {subject_slug}")
        if difficulty not in VALID_DIFFICULTIES:
            raise ValueError(f"Line {line_number}: invalid difficulty {difficulty}")
        if correct_option not in VALID_ANSWERS or not options[correct_option]:
            raise ValueError(f"Line {line_number}: invalid correct option")
        if any(not value or value.upper() == "N/A" for value in options.values()):
            raise ValueError(f"Line {line_number}: missing required option A-D")

        ids.add(external_id)
        subject_counts[subject_slug] += 1
        usage_counts[usage_type] += 1
        rows.append(
            {
                **required,
                "chapter_num": int(clean(source_row.get("chapter_num")) or 0),
                # CSV uses "question", but these fields describe topic nodes.
                "node_kind": "topic",
                "option_a": options["a"],
                "option_b": options["b"],
                "option_c": options["c"],
                "option_d": options["d"],
                # option_e is deliberately excluded: every source row contains N/A.
                "correct_option": correct_option,
                "explanation": clean(source_row.get("explanation")) or None,
                "difficulty": difficulty,
                "source": source_label,
                "usage_type": usage_type,
            }
        )

    if dict(subject_counts) != EXPECTED_SUBJECT_COUNTS:
        raise ValueError(f"Unexpected subject counts: {dict(subject_counts)}")
    if dict(usage_counts) != EXPECTED_USAGE_COUNTS:
        raise ValueError(f"Unexpected usage counts: {dict(usage_counts)}")
    return rows


def build_sql(rows: list[dict[str, object]]) -> str:
    payload = json.dumps(rows, ensure_ascii=False, separators=(",", ":"))
    if "$fast_questions$" in payload:
        raise ValueError("Migration delimiter occurs in CSV data")

    return f"""-- Generated by scripts/generate_fast_migration.py.
-- Adds FAST-NUCES Computing and imports its normalized 1,000-question bank.
begin;

insert into entry_tests (
  external_id, slug, name, description, source, is_active, display_order
)
values (
  'fast-nuces-computing',
  'fast',
  'FAST-NUCES Computing',
  'Topic-based preparation for the FAST-NUCES computing admission test.',
  'FAST-NUCES computing question bank',
  true,
  40
)
on conflict (external_id) do update set
  slug = excluded.slug,
  name = excluded.name,
  description = excluded.description,
  source = excluded.source,
  is_active = excluded.is_active,
  display_order = excluded.display_order;

insert into subjects (external_id, slug, name)
values
  ('advanced-mathematics', 'advanced-mathematics', 'Advanced Mathematics'),
  ('basic-mathematics', 'basic-mathematics', 'Basic Mathematics'),
  ('iq-analytical-reasoning', 'iq-analytical-reasoning', 'IQ & Analytical Reasoning'),
  ('english', 'english', 'English')
on conflict (external_id) do update set name = excluded.name;

insert into test_subjects (
  entry_test_id, subject_id, nature_of_questions, difficulty_profile,
  display_order, is_active, deleted_at
)
select test.id, subject.id, config.nature, config.profile, config.ord, true, null
from entry_tests test
cross join (values
  ('advanced-mathematics', 'Intermediate and advanced mathematics for computing admissions', '{{"easy":125,"medium":209,"hard":83}}'::jsonb, 0),
  ('basic-mathematics', 'Arithmetic, commercial mathematics, and quantitative problem solving', '{{"easy":50,"medium":84,"hard":33}}'::jsonb, 1),
  ('iq-analytical-reasoning', 'Series, coding, directions, relations, and analytical arrangements', '{{"easy":50,"medium":84,"hard":33}}'::jsonb, 2),
  ('english', 'Grammar, vocabulary, sentence correction, and comprehension', '{{"easy":75,"medium":123,"hard":51}}'::jsonb, 3)
) as config(subject_slug, nature, profile, ord)
join subjects subject on subject.slug = config.subject_slug
where test.slug = 'fast'
on conflict (entry_test_id, subject_id) do update set
  nature_of_questions = excluded.nature_of_questions,
  difficulty_profile = excluded.difficulty_profile,
  display_order = excluded.display_order,
  is_active = true,
  deleted_at = null;

create temporary table fast_import_stage on commit drop as
select *
from jsonb_to_recordset($fast_questions${payload}$fast_questions$::jsonb) as row_data(
  external_id text,
  subject text,
  subject_slug text,
  chapter_num integer,
  chapter_slug text,
  chapter_title text,
  node_kind text,
  statement text,
  option_a text,
  option_b text,
  option_c text,
  option_d text,
  correct_option text,
  explanation text,
  difficulty text,
  source text,
  usage_type text
);

insert into topics (
  external_id, subject_id, kind, title, slug, display_order, deleted_at
)
select distinct on (stage.subject_slug, stage.chapter_slug)
  'fast-' || stage.subject_slug || '-' || stage.chapter_slug,
  subject.id,
  stage.node_kind::topic_kind,
  stage.chapter_title,
  stage.chapter_slug,
  stage.chapter_num,
  null
from fast_import_stage stage
join subjects subject on subject.slug = stage.subject_slug
order by stage.subject_slug, stage.chapter_slug, stage.chapter_num
on conflict (external_id) do update set
  subject_id = excluded.subject_id,
  kind = excluded.kind,
  title = excluded.title,
  slug = excluded.slug,
  display_order = excluded.display_order,
  deleted_at = null;

insert into questions (
  external_id, subject_id, topic_id, difficulty, statement,
  explanation, source, moderation_status, review_note, deleted_at
)
select
  stage.external_id,
  subject.id,
  topic.id,
  stage.difficulty::difficulty,
  stage.statement,
  stage.explanation,
  stage.source,
  'approved'::moderation_status,
  null,
  null
from fast_import_stage stage
join subjects subject on subject.slug = stage.subject_slug
join topics topic
  on topic.external_id = 'fast-' || stage.subject_slug || '-' || stage.chapter_slug
on conflict (external_id) do update set
  subject_id = excluded.subject_id,
  topic_id = excluded.topic_id,
  difficulty = excluded.difficulty,
  statement = excluded.statement,
  explanation = excluded.explanation,
  source = excluded.source,
  moderation_status = excluded.moderation_status,
  review_note = null,
  deleted_at = null;

update question_options option_row
set is_correct = false
from questions question
join fast_import_stage stage on stage.external_id = question.external_id
where option_row.question_id = question.id;

delete from question_options option_row
using questions question, fast_import_stage stage
where option_row.question_id = question.id
  and question.external_id = stage.external_id
  and option_row.option_label not in ('a', 'b', 'c', 'd');

insert into question_options (
  question_id, option_label, content, is_correct, display_order
)
select
  question.id,
  option_data.label,
  option_data.content,
  option_data.label = stage.correct_option,
  option_data.ord
from fast_import_stage stage
join questions question on question.external_id = stage.external_id
cross join lateral (values
  ('a', stage.option_a, 0),
  ('b', stage.option_b, 1),
  ('c', stage.option_c, 2),
  ('d', stage.option_d, 3)
) as option_data(label, content, ord)
on conflict (question_id, option_label) do update set
  content = excluded.content,
  is_correct = excluded.is_correct,
  display_order = excluded.display_order;

insert into question_tests (
  question_id, entry_test_id, usage_type, difficulty, paper_session
)
select
  question.id,
  test.id,
  stage.usage_type::question_usage,
  stage.difficulty::difficulty,
  case when stage.usage_type = 'past_paper' then 'Past-paper style' else null end
from fast_import_stage stage
join questions question on question.external_id = stage.external_id
cross join entry_tests test
where test.slug = 'fast'
on conflict (question_id, entry_test_id) do update set
  usage_type = excluded.usage_type,
  difficulty = excluded.difficulty,
  source_year = null,
  paper_session = excluded.paper_session;

do $$
declare
  imported_count integer;
  topic_count integer;
  past_paper_count integer;
  practice_count integer;
  invalid_question_count integer;
begin
  select
    count(*),
    count(*) filter (where link.usage_type = 'past_paper'),
    count(*) filter (where link.usage_type = 'practice')
  into imported_count, past_paper_count, practice_count
  from question_tests link
  join entry_tests test on test.id = link.entry_test_id
  join questions question on question.id = link.question_id
  where test.slug = 'fast' and question.external_id like 'FAST-%';

  select count(distinct question.topic_id) into topic_count
  from question_tests link
  join entry_tests test on test.id = link.entry_test_id
  join questions question on question.id = link.question_id
  where test.slug = 'fast' and question.external_id like 'FAST-%';

  select count(*) into invalid_question_count
  from (
    select question.id
    from fast_import_stage stage
    join questions question on question.external_id = stage.external_id
    join question_options option_row on option_row.question_id = question.id
    group by question.id
    having count(*) <> 4
       or count(*) filter (where option_row.is_correct) <> 1
  ) invalid;

  if imported_count <> 1000 or topic_count <> 45 then
    raise exception 'FAST import expected 1000 questions/45 topics, found %/%',
      imported_count, topic_count;
  end if;
  if past_paper_count <> 394 or practice_count <> 606 then
    raise exception 'FAST usage split expected 394/606, found %/%',
      past_paper_count, practice_count;
  end if;
  if invalid_question_count <> 0 then
    raise exception 'FAST import found % questions with invalid options/answer keys',
      invalid_question_count;
  end if;
end $$;

commit;
"""


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv", type=Path, default=DEFAULT_CSV)
    args = parser.parse_args()
    rows = load_rows(args.csv)
    OUTPUT_PATH.write_text(build_sql(rows), encoding="utf-8")
    print(
        f"Generated {OUTPUT_PATH.relative_to(ROOT)} with {len(rows)} questions "
        f"(394 past paper, 606 practice)"
    )


if __name__ == "__main__":
    main()
